# Generated by Django 5.1.2 on 2025-02-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='destino',
        ),
        migrations.AddField(
            model_name='atividade',
            name='roteiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='roteiros.roteiro'),
            preserve_default=False,
        ),
    ]
