# Generated by Django 5.1.2 on 2025-02-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0002_remove_atividade_destino_atividade_roteiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='destino',
            new_name='roteiro',
        ),
        migrations.RenameField(
            model_name='restaurante',
            old_name='destino',
            new_name='roteiro',
        ),
    ]
