# Generated by Django 5.1.2 on 2025-02-25 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0003_rename_destino_pontoturistico_roteiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='roteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_turisticos', to='roteiros.roteiro'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='roteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to='roteiros.roteiro'),
        ),
    ]
